# Generated by Django 4.1.1 on 2022-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creater', models.CharField(max_length=255)),
                ('title_guide', models.CharField(max_length=255)),
                ('content_guide', models.TextField()),
                ('date_create', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
