# Generated by Django 4.1.1 on 2022-10-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_categoriesguide_guidemodel_answer_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidemodel',
            name='answer_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.categoriesguide'),
        ),
    ]
