# Generated by Django 4.1.1 on 2022-10-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_guidemodel_answer_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidemodel',
            old_name='answer_to',
            new_name='categories',
        ),
    ]
