# Generated by Django 4.1.1 on 2022-10-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_guidemodel_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidemodel',
            name='guide_slug',
            field=models.CharField(default='default', max_length=50, null=True),
        ),
    ]
